# SwiftLint Configuration File
# https://github.com/realm/SwiftLint

# Paths to exclude from linting
excluded:
  - Pods
  - .build
  - DerivedData
  - movieApp.xcodeproj
  - movieApp.xcworkspace
  - Package.swift

# Rules that are disabled by default but should be enabled
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
  - sorted_first_last
  - explicit_init
  - multiline_parameters
  - multiline_arguments
  - toggle_bool
  - unused_optional_binding
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rules to disable
disabled_rules:
  - trailing_whitespace # Let editor handle this
  - identifier_name # Allow short names like 'id', 'vm', 'vc'

# Configuration for specific rules

# Line length
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 400

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting depth
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Force cast/unwrap - allow in tests
force_cast: warning
force_unwrap: warning
force_try: warning

# Type name
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - URL

# Function parameter count
function_parameter_count:
  warning: 5
  error: 8

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Trailing closure
trailing_closure:
  only_single_muted_parameter: true

# Custom rules
custom_rules:
  # Ensure print statements are not committed to production code
  no_print:
    name: "Print Statement"
    regex: "print\\("
    match_kinds:
      - identifier
    message: "Avoid using print() in production code. Use proper logging."
    severity: warning
    
  # Discourage force unwrapping in non-test code
  force_unwrap_non_test:
    name: "Force Unwrap"
    regex: "!(?!\\s*//)"
    match_kinds:
      - identifier
    excluded: ".*Tests\\.swift"
    message: "Avoid force unwrapping. Use optional binding instead."
    severity: warning

# Reporter type
reporter: "xcode"

# Run SwiftLint in strict mode (warnings treated as errors)
# Uncomment when ready for strict enforcement
# strict: true

